# Generated by Django 3.2.7 on 2021-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvid', models.PositiveIntegerField(default=0, help_text='Google Excel編號')),
                ('pazeh', models.CharField(db_index=True, help_text='Pazeh文字項目', max_length=255)),
                ('hua', models.CharField(db_index=True, help_text='Pazeh華語解說項目', max_length=255)),
                ('pageid', models.PositiveIntegerField(default=0, help_text='原始頁碼')),
            ],
        ),
    ]
